import = ["C:/Users/cleit/AppData/Roaming/alacritty/themes/themes/nordic.toml"]

[shell]
program = "ubuntu2204"

[window]
title = "alacritty"
dynamic_title = false
decorations = "none"

[window.padding]
x = 5
y = 0

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
